disabled_rules:
  - leading_whitespace
  - trailing_whitespace
  - identifier_name
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - function_body_length
  - large_tuple
  - nesting

excluded:
  - Pods/

line_length:
  warning: 99
  error: 120
